# -*- coding: utf-8 -*-
"""Term Paper1.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Mh0vzCa0Go1HEIVQDZC599DKoqiOo89U

# **Lightweight CNN Model for Efficient Pneumonia Detection from Chest X-Ray Images**

# **Image amount check**
"""

import os

# Set the path to your main dataset folder (update this)
dataset_path = '/content/drive/MyDrive/CHESTXRAY/'  # example path

# List subfolders (Normal and Pneumonia)
folders = os.listdir(dataset_path)

print("📂 Dataset summary:\n")
for folder in folders:
    folder_path = os.path.join(dataset_path, folder)
    if os.path.isdir(folder_path):
        num_images = len(os.listdir(folder_path))
        print(f"{folder}: {num_images} images")

"""# **Visualize samples**"""

import os
import matplotlib.pyplot as plt
import random
import cv2

# Path to dataset
dataset_path = '/content/drive/MyDrive/CHESTXRAY/'

# List of classes
classes = ['NORMAL', 'PNEUMONIA']

plt.figure(figsize=(10, 6))

for i, cls in enumerate(classes):
    folder_path = os.path.join(dataset_path, cls)
    # Pick 3 random images from the folder
    sample_images = random.sample(os.listdir(folder_path), 3)

    for j, img_name in enumerate(sample_images):
        img_path = os.path.join(folder_path, img_name)
        img = cv2.imread(img_path)
        img = cv2.cvtColor(img, cv2.COLOR_BGR2RGB)

        plt.subplot(2, 3, i*3 + j + 1)
        plt.imshow(img)
        plt.title(cls)
        plt.axis('off')

plt.suptitle("Sample Chest X-ray Images (Normal vs Pneumonia)", fontsize=14)
plt.tight_layout()
plt.show()

"""# **Resizing to 224x224**"""

import os
import cv2
from tqdm import tqdm

# Paths
input_dir = '/content/drive/MyDrive/CHESTXRAY/'          # original folder
output_dir = '/content/drive/MyDrive/CHESTXRAY_RESIZED/' # resized folder
target_size = (224, 224)  # resize size (width, height)

# Create output directories if not exist
os.makedirs(output_dir, exist_ok=True)

# Loop through each class folder (NORMAL, PNEUMONIA)
for folder in os.listdir(input_dir):
    input_folder = os.path.join(input_dir, folder)
    output_folder = os.path.join(output_dir, folder)

    if not os.path.isdir(input_folder):
        continue  # skip files

    os.makedirs(output_folder, exist_ok=True)

    print(f"Processing {folder}...")

    # Loop through images in each folder
    for img_name in tqdm(os.listdir(input_folder)):
        img_path = os.path.join(input_folder, img_name)

        try:
            # Read image
            img = cv2.imread(img_path)
            if img is None:
                continue

            # Resize
            img_resized = cv2.resize(img, target_size)

            # Save resized image to output folder
            save_path = os.path.join(output_folder, img_name)
            cv2.imwrite(save_path, img_resized)

        except Exception as e:
            print(f"Error processing {img_name}: {e}")

print("\n✅ All images resized and saved successfully in:", output_dir)

"""# **Preprocessing**"""

import os
import cv2
import numpy as np
from tqdm import tqdm

input_dir = '/content/drive/MyDrive/CHESTXRAY_RESIZED/'
output_dir = '/content/drive/MyDrive/CHESTXRAY_PREPROCESSED_V2/'

os.makedirs(output_dir, exist_ok=True)

for folder in os.listdir(input_dir):
    input_folder = os.path.join(input_dir, folder)
    output_folder = os.path.join(output_dir, folder)

    if not os.path.isdir(input_folder):
        continue

    os.makedirs(output_folder, exist_ok=True)
    print(f"Processing {folder}...")

    for img_name in tqdm(os.listdir(input_folder)):
        img_path = os.path.join(input_folder, img_name)
        img = cv2.imread(img_path, cv2.IMREAD_GRAYSCALE)
        if img is None:
            continue

        # --- Step 1: Denoise using Median Filter (preserves edges) ---
        #img_denoised = cv2.medianBlur(img, 3)

        # --- Step 2: Contrast enhancement using CLAHE ---
        clahe = cv2.createCLAHE(clipLimit=2.0, tileGridSize=(6,6))
        img_clahe = clahe.apply(img)

        # --- Step 3: Gamma correction (optional, improves brightness) ---
        gamma = 1.2  # try between 1.0 and 1.5
        img_gamma = np.power(img_clahe / 255.0, gamma)

        # --- Step 4: Normalize to 0–1 ---
        img_norm = (img_gamma - np.min(img_gamma)) / (np.max(img_gamma) - np.min(img_gamma))

        # --- Save ---
        save_path = os.path.join(output_folder, img_name)
        img_to_save = np.uint8(img_norm * 255)
        cv2.imwrite(save_path, img_to_save)

print("\n✅ Improved preprocessing completed and saved in:", output_dir)
